spring:
  druidDataSource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#        初始化连接大小
    initialSize: 0
#        连接池最大使用连接数量
    maxActive: 20
#        连接池最小空闲
    minIdle: 1
#        获取连接最大等待时间
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 33
#        用来检测有效sql
    validationQuery: select 1
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
#        配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
#        配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
#        打开removeAbandoned功能
    removeAbandoned: true
#        1800秒，也就是30分钟
    removeAbandonedTimeout: 1800
#        关闭abanded连接时输出错误日志
    logAbandoned: true
#        监控数据库
    filters: mergeStat